# Project information
site_name: loudflow
site_url: https://farsimple.com/loudflow
site_author: Sinan Inel

# Repository
repo_name: farsimple/loudflow
repo_url: https://github.com/farsimple/loudflow
edit_uri: edit/master/docs
docs_dir: docs

# Navigation
nav:
  - Welcome: index.md
  - Code Reference:
    - loudflow:
      - main: loudflow/main-reference.md
      - realm:
        - realm: loudflow/realm/realm-reference.md
        - action:
          - action: loudflow/realm/action/action-reference.md
          - move: loudflow/realm/action/move-reference.md
        - display:
          - change: loudflow/realm/display/change-reference.md
          - console: loudflow/realm/display/console-reference.md
          - display: loudflow/realm/display/display-reference.md
        - event:
          - action_event: loudflow/realm/event/action-event-reference.md
          - event: loudflow/realm/event/event-reference.md
          - update_event: loudflow/realm/event/update-event-reference.md
        - thing:
          - action: loudflow/realm/thing/thing-reference.md
        - world:
          - world: loudflow/realm/world/world-reference.md
      - common:
        - decorators: loudflow/common/decorators-reference.md

# Theme
theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.expand
    - navigation.instant
    - navigation.tabs
    - navigation.top
  palette:
    scheme: default
    primary: black
    accent: indigo

# Plugins
plugins:
  - git-revision-date
  - mkdocstrings
  - search

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - meta
  - toc:
      permalink: true
      toc_depth: 3
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
