name: ci
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  integration:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: poetry
      run: |
        curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python -
        echo "${HOME}/.poetry/bin" >> $GITHUB_PATH
    - name: dependencies
      run: |
        sudo apt update
        sudo apt-get install libsdl2-dev
        poetry install
    - name: flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        poetry run flake8 src --count --statistics --show-source --select=E9,F63,F7,F82
        # exit-zero treats all errors as warnings
        poetry run flake8 src --count --statistics --show-source --exit-zero --max-line-length=120
    - name: black
      run: |
        poetry run black src --diff --check
    - name: isort
      run: |
        poetry run isort src --check-only
    - name: mypy
      run: |
        poetry run mypy src
    - name: tox
      run: |
        poetry run tox
    - name: docs
      run: |
        poetry run mkdocs gh-deploy --force
